GET http://localhost:1234/movies
### Recuperar una pelicula por id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar pelicula por genero con query params
GET http://localhost:1234/movies?genre=crime


### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Midupelo",
    "year": 1996,
    "director": "Francisco Ferreira Darabont",
    "duration": 142,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
      "Drama"
    ],
    "rate": 9.3
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
Content-Type: application/json

{
    "year": 2002
}